# Generated by Django 4.2.28 on 2026-02-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-startYear',)},
        ),
        migrations.AddField(
            model_name='project',
            name='blog_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
